
from pathlib import Path
import hashlib
import pandas as pd


PROJECT_ROOT = Path(r"D:\Biosential_India")

SOURCE_MANIFEST = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "inaturalist"
    / "efficientnet_manifest.csv"
)

IMAGE_ROOT = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "inaturalist"
    / "images"
)

OUTPUT_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "inaturalist"
)

OUTPUT_MANIFEST = (
    OUTPUT_DIR
    / "efficientnet_30_reuse_manifest.csv"
)

OUTPUT_AUDIT = (
    OUTPUT_DIR
    / "efficientnet_30_reuse_audit.csv"
)

MAX_IMAGES_PER_SPECIES = 30

# Preferred split composition.
TARGET_SPLIT_COUNTS = {
    "train": 21,
    "val": 4,
    "test": 5,
}

SEED = 42

SUPPORTED_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
}


def extension_from_format(media_format: str, url: str) -> str:
    fmt = str(media_format or "").strip().lower()

    if fmt == "image/jpeg":
        return ".jpg"

    if fmt == "image/pjpeg":
        return ".jpg"

    if fmt == "image/png":
        return ".png"

    suffix = Path(str(url)).suffix.lower()

    if suffix in SUPPORTED_EXTENSIONS:
        return suffix

    return ".jpg"


def make_filename(row: pd.Series) -> str:
    gbif_id = str(row["gbifID"]).strip()
    url = str(row["image_url"]).strip()

    url_hash = hashlib.sha1(
        url.encode("utf-8")
    ).hexdigest()[:12]

    ext = extension_from_format(
        row.get("media_format", ""),
        url,
    )

    return f"{gbif_id}__{url_hash}{ext}"


def build_existing_filename_index():
    """
    Index every already-downloaded image below IMAGE_ROOT.

    We index by the deterministic filename used by the original downloader.
    This lets us recognize images downloaded during the previous 193k-image
    run even though the new 30-image selection is different.
    """
    index = {}

    if not IMAGE_ROOT.exists():
        return index

    for path in IMAGE_ROOT.rglob("*"):
        if not path.is_file():
            continue

        if path.suffix.lower() not in SUPPORTED_EXTENSIONS:
            continue

        index.setdefault(
            path.name,
            []
        ).append(path)

    return index


def stable_order(df, species_key, split, label):
    """
    Deterministic ordering for rows that are otherwise interchangeable.
    """
    result = df.copy()

    result["_hash"] = result["image_url"].astype(str).map(
        lambda value: hashlib.sha256(
            f"{species_key}:{split}:{label}:{value}:{SEED}"
            .encode("utf-8")
        ).hexdigest()
    )

    return result.sort_values(
        "_hash",
        kind="stable",
    )


def select_species(group, existing_index):
    """
    Reuse-first selection.

    Phase A:
      Use existing images first to satisfy the preferred 21/4/5 split
      quotas.

    Phase B:
      If existing images remain but a split quota was not possible, use
      existing images from another split to reach 30 rather than downloading
      replacements.

    Phase C:
      Download only the remaining number needed to reach 30, prioritizing
      the unmet split quotas.

    All source rows already have the leakage-safe split generated by the
    previous preparation pipeline, so no occurrence is moved between splits.
    """
    species_key = group.iloc[0]["speciesKey"]

    work = group.copy()

    work["_filename"] = work.apply(
        make_filename,
        axis=1,
    )

    work["_existing"] = work["_filename"].map(
        lambda name: name in existing_index
    )

    selected_indices = set()

    # ------------------------------------------------------------------
    # A. Existing files first, per preferred split quota.
    # ------------------------------------------------------------------
    for split, target in TARGET_SPLIT_COUNTS.items():

        candidates = work[
            (work["split"] == split)
            & (work["_existing"])
        ].copy()

        if candidates.empty:
            continue

        candidates = stable_order(
            candidates,
            species_key,
            split,
            "existing",
        )

        for idx in candidates.index[:target]:
            selected_indices.add(idx)

    # ------------------------------------------------------------------
    # B. Use additional EXISTING files if we still have fewer than 30.
    # This is the crucial improvement over the previous downloader.
    #
    # Example:
    #   25 existing train images + 0 existing val/test
    #   -> keep those 25 instead of discarding 4 and downloading new ones.
    # ------------------------------------------------------------------
    remaining_existing = work[
        (work["_existing"])
        & (~work.index.isin(selected_indices))
    ].copy()

    if not remaining_existing.empty:

        remaining_existing = stable_order(
            remaining_existing,
            species_key,
            "any",
            "existing_fill",
        )

        slots = MAX_IMAGES_PER_SPECIES - len(
            selected_indices
        )

        for idx in remaining_existing.index[:slots]:
            selected_indices.add(idx)

    # ------------------------------------------------------------------
    # C. Fill missing slots from rows that are NOT already downloaded.
    # Respect split deficits first.
    # ------------------------------------------------------------------
    needed = MAX_IMAGES_PER_SPECIES - len(
        selected_indices
    )

    if needed > 0:

        selected = work.loc[
            list(selected_indices)
        ].copy()

        split_counts = (
            selected["split"]
            .value_counts()
            .to_dict()
        )

        deficits = {
            split: max(
                TARGET_SPLIT_COUNTS[split]
                - split_counts.get(split, 0),
                0,
            )
            for split in TARGET_SPLIT_COUNTS
        }

        for split in [
            "train",
            "val",
            "test",
        ]:

            if needed <= 0:
                break

            candidates = work[
                (work["split"] == split)
                & (~work.index.isin(selected_indices))
            ].copy()

            if candidates.empty:
                continue

            candidates = stable_order(
                candidates,
                species_key,
                split,
                "new",
            )

            take = min(
                deficits[split],
                needed,
                len(candidates),
            )

            for idx in candidates.index[:take]:
                selected_indices.add(idx)

            needed -= take

    # If split deficits couldn't fill all slots, fill from any remaining
    # unseen rows. This does not introduce leakage because we keep the
    # source row's original split.
    if needed > 0:

        candidates = work[
            ~work.index.isin(selected_indices)
        ].copy()

        candidates = stable_order(
            candidates,
            species_key,
            "any",
            "new_fill",
        )

        for idx in candidates.index[:needed]:
            selected_indices.add(idx)

    selected = work.loc[
        sorted(selected_indices)
    ].copy()

    # Safety.
    if len(selected) > MAX_IMAGES_PER_SPECIES:
        raise RuntimeError(
            f"Species {species_key} exceeded 30 images."
        )

    return selected


def main():

    print("=" * 100)
    print("BIOSENTINEL INDIA — REUSE-FIRST 30 IMAGE MANIFEST")
    print("=" * 100)

    if not SOURCE_MANIFEST.exists():
        raise FileNotFoundError(
            f"Source manifest not found:\n{SOURCE_MANIFEST}"
        )

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    print("\nLoading source manifest...")

    df = pd.read_csv(
        SOURCE_MANIFEST,
        low_memory=False,
    )

    required = {
        "gbifID",
        "species",
        "speciesKey",
        "species_folder",
        "split",
        "image_url",
    }

    missing = required - set(df.columns)

    if missing:
        raise ValueError(
            f"Missing columns: {sorted(missing)}"
        )

    df["gbifID"] = (
        df["gbifID"]
        .astype("string")
        .str.strip()
    )

    df["speciesKey"] = (
        df["speciesKey"]
        .astype("string")
        .str.strip()
    )

    print(
        f"Source rows: {len(df):,}"
    )

    print(
        f"Source species: "
        f"{df['speciesKey'].nunique():,}"
    )

    print("\nIndexing existing images...")

    existing_index = (
        build_existing_filename_index()
    )

    existing_file_count = sum(
        len(v)
        for v in existing_index.values()
    )

    print(
        f"Existing image files on disk: "
        f"{existing_file_count:,}"
    )

    # ------------------------------------------------------------------
    # Build reuse-first selection.
    # ------------------------------------------------------------------

    print(
        "\nSelecting maximum 30 images/species "
        "with existing-file reuse..."
    )

    parts = []

    for species_key, group in df.groupby(
        "speciesKey",
        sort=True,
        dropna=False,
    ):
        selected = select_species(
            group,
            existing_index,
        )

        parts.append(selected)

    final_df = pd.concat(
        parts,
        ignore_index=True,
    )

    final_df = final_df.drop(
        columns=[
            "_filename",
            "_existing",
            "_hash",
        ],
        errors="ignore",
    )

    # ------------------------------------------------------------------
    # Audit selected rows.
    # ------------------------------------------------------------------

    final_df["_filename_audit"] = final_df.apply(
        make_filename,
        axis=1,
    )

    final_df["_existing_audit"] = (
        final_df["_filename_audit"].map(
            lambda name: name in existing_index
        )
    )

    species_counts = (
        final_df.groupby("speciesKey")
        .size()
    )

    if (
        len(species_counts) != 1_106
        or species_counts.min() != 30
        or species_counts.max() != 30
    ):
        raise RuntimeError(
            "Final selection does not contain exactly "
            "30 images for every species."
        )

    # Ensure no GBIF occurrence appears in multiple splits.
    occurrence_split_counts = (
        final_df.groupby("gbifID")["split"]
        .nunique()
    )

    leakage = occurrence_split_counts[
        occurrence_split_counts > 1
    ]

    if len(leakage):
        raise RuntimeError(
            f"Occurrence leakage detected: "
            f"{len(leakage):,} GBIF IDs span multiple splits."
        )

    # ------------------------------------------------------------------
    # Print summary.
    # ------------------------------------------------------------------

    reusable = int(
        final_df["_existing_audit"].sum()
    )

    need_download = (
        len(final_df) - reusable
    )

    print("\n" + "=" * 100)
    print("REUSE-FIRST DATASET SUMMARY")
    print("=" * 100)

    print(
        f"\nSpecies:               "
        f"{final_df['speciesKey'].nunique():,}"
    )

    print(
        f"Target images:         "
        f"{len(final_df):,}"
    )

    print(
        f"Already on disk/reused: "
        f"{reusable:,}"
    )

    print(
        f"Actually need download: "
        f"{need_download:,}"
    )

    print(
        f"Reuse percentage:      "
        f"{reusable / len(final_df) * 100:.2f}%"
    )

    print("\nSplit distribution:")

    print(
        final_df["split"]
        .value_counts()
        .reindex(
            ["train", "val", "test"]
        )
        .to_string()
    )

    print("\nExisting vs missing by split:")

    audit = (
        final_df.groupby("split")
        .agg(
            images=("image_url", "size"),
            existing=(
                "_existing_audit",
                "sum",
            ),
        )
        .reindex(
            ["train", "val", "test"]
        )
    )

    audit["need_download"] = (
        audit["images"]
        - audit["existing"]
    )

    print(audit.to_string())

    # Remove audit columns before final manifest.
    final_df = final_df.drop(
        columns=[
            "_filename_audit",
            "_existing_audit",
        ]
    )

    final_df.to_csv(
        OUTPUT_MANIFEST,
        index=False,
    )

    # Save audit.
    audit.reset_index().to_csv(
        OUTPUT_AUDIT,
        index=False,
    )

    print("\nOutputs:")
    print(OUTPUT_MANIFEST)
    print(OUTPUT_AUDIT)

    print("\nDATA LEAKAGE CHECK: PASSED")
    print("=" * 100)


if __name__ == "__main__":
    main()
